version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: docker/Dockerfile
    container_name: laravel_app
    restart: unless-stopped
    working_dir: /var/www/html
    volumes:
      - .:/var/www/html
    ports:
      - "8000:80"
    environment:
      - DB_HOST=db
      - DB_DATABASE=biblioteca
      - DB_USERNAME=root
      - DB_PASSWORD=root
      - APP_ENV=local
      - APP_DEBUG=true
      - APP_KEY=base64:WcL4eYwXyN8m7S79fzPPlGI/PXkP+VBLYQgmise60os=
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: mysql_db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: biblioteca
      MYSQL_USER: biblioteca
      MYSQL_PASSWORD: root
    volumes:
      - dbdata:/var/lib/mysql
    ports:
      - "3306:3306"

volumes:
  dbdata:
    driver: local
